
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckPaymentService", targetNamespace = "http://check_payment/", wsdlLocation = "http://localhost:8082/CheckPayment?wsdl")
public class CheckPaymentService_Service
    extends Service
{

    private final static URL CHECKPAYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKPAYMENTSERVICE_EXCEPTION;
    private final static QName CHECKPAYMENTSERVICE_QNAME = new QName("http://check_payment/", "CheckPaymentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/CheckPayment?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKPAYMENTSERVICE_WSDL_LOCATION = url;
        CHECKPAYMENTSERVICE_EXCEPTION = e;
    }

    public CheckPaymentService_Service() {
        super(__getWsdlLocation(), CHECKPAYMENTSERVICE_QNAME);
    }

    public CheckPaymentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKPAYMENTSERVICE_QNAME, features);
    }

    public CheckPaymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, CHECKPAYMENTSERVICE_QNAME);
    }

    public CheckPaymentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKPAYMENTSERVICE_QNAME, features);
    }

    public CheckPaymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckPaymentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckPaymentService
     */
    @WebEndpoint(name = "CheckPaymentPort")
    public CheckPaymentService getCheckPaymentPort() {
        return super.getPort(new QName("http://check_payment/", "CheckPaymentPort"), CheckPaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckPaymentService
     */
    @WebEndpoint(name = "CheckPaymentPort")
    public CheckPaymentService getCheckPaymentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://check_payment/", "CheckPaymentPort"), CheckPaymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKPAYMENTSERVICE_EXCEPTION!= null) {
            throw CHECKPAYMENTSERVICE_EXCEPTION;
        }
        return CHECKPAYMENTSERVICE_WSDL_LOCATION;
    }

}
